/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DatingAppInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allUsers"
      | "createProfile"
      | "getAllUsers"
      | "getProfile"
      | "getReceivedMessages"
      | "getSentMessages"
      | "profiles"
      | "receivedMessages"
      | "sendMessage"
      | "sentMessages"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MessageSent" | "ProfileCreated" | "ProfileUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProfile",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceivedMessages",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSentMessages",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receivedMessages",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sentMessages",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReceivedMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSentMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receivedMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentMessages",
    data: BytesLike
  ): Result;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    encryptedMessage: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    encryptedMessage: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    encryptedMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileCreatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DatingApp extends BaseContract {
  connect(runner?: ContractRunner | null): DatingApp;
  waitForDeployment(): Promise<this>;

  interface: DatingAppInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createProfile: TypedContractMethod<
    [avatar: string, socialLinks: string, description: string],
    [void],
    "nonpayable"
  >;

  getAllUsers: TypedContractMethod<[], [string[]], "view">;

  getProfile: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        owner: string;
        avatar: string;
        socialLinks: string;
        description: string;
        exists: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getReceivedMessages: TypedContractMethod<
    [user: AddressLike],
    [
      [string[], string[], bigint[]] & {
        from: string[];
        messages: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  getSentMessages: TypedContractMethod<
    [user: AddressLike],
    [
      [string[], string[], bigint[]] & {
        to: string[];
        messages: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        owner: string;
        avatar: string;
        socialLinks: string;
        description: string;
        exists: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  receivedMessages: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        from: string;
        to: string;
        encryptedMessage: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  sendMessage: TypedContractMethod<
    [to: AddressLike, encryptedMessage: BytesLike, arg2: BytesLike],
    [void],
    "nonpayable"
  >;

  sentMessages: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        from: string;
        to: string;
        encryptedMessage: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createProfile"
  ): TypedContractMethod<
    [avatar: string, socialLinks: string, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllUsers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        owner: string;
        avatar: string;
        socialLinks: string;
        description: string;
        exists: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceivedMessages"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string[], string[], bigint[]] & {
        from: string[];
        messages: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSentMessages"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string[], string[], bigint[]] & {
        to: string[];
        messages: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        owner: string;
        avatar: string;
        socialLinks: string;
        description: string;
        exists: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "receivedMessages"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        from: string;
        to: string;
        encryptedMessage: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [to: AddressLike, encryptedMessage: BytesLike, arg2: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sentMessages"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        from: string;
        to: string;
        encryptedMessage: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;
  getEvent(
    key: "ProfileCreated"
  ): TypedContractEvent<
    ProfileCreatedEvent.InputTuple,
    ProfileCreatedEvent.OutputTuple,
    ProfileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;

  filters: {
    "MessageSent(address,address,bytes32)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;

    "ProfileCreated(address)": TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
    ProfileCreated: TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;

    "ProfileUpdated(address)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
  };
}
