/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DatingApp } from "./DatingApp";
export * as factories from "./factories";
export { DatingApp__factory } from "./factories/DatingApp__factory";
